baseURL = 'https://joseph-mccarthy.github.io'
languageCode = 'en-us'
title = 'Joseph McCarthy'

theme = "freelancer"
summaryLength=40
paginate=6



[params]
  tagLine = "Developer - Dreamer - Potato"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization."
  aboutRight = "You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!"

[params.location]
  lineOne = "Harlow, Essex"
  lineTwo = "United Kingdom" 

[params.sbform]
      token = ""

# [params.homebutton]
#  text = "Free Donwload"
#  link = "https://startbootstrap.com/theme/freelancer/" 
#  icon = "fa-download"


[[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/joseph-mccarthy"
[[params.social]]
      icon      = "twitter" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://twitter.com/joebmccarthy"
[[params.social]]
      icon      = "facebook" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://www.facebook.com/joebmccarthy/"


[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
