baseURL = 'https://joseph-mccarthy.github.io'
languageCode = 'en-us'
title = 'Joseph McCarthy'

theme = "freelancer"
summaryLength=40
paginate=9


[params]
  tagLine = "Developer - Dreamer - Potato"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "I work full time as a Java Developer, however I love to tinker and build things. So I also spend a lot of time out of work coding as well."
  aboutRight = "I've created this little slice of the internet, to keep track of what I do, and give me something to look back on from time to time."

[params.location]
  lineOne = "Harlow, Essex"
  lineTwo = "United Kingdom" 

[params.sbform]
      token = ""

[[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/joseph-mccarthy"


[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[markup]
  [markup.highlight]
    margin = 10
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'friendly'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
     [outputFormats.RSS]
         mediaType = "application/rss+xml"
         baseName = "feed"
