baseURL = 'https://joseph-mccarthy.github.io'
languageCode = 'en-us'
title = 'Start Bootstrap'

theme = "default"
summaryLength=20
paginate=9



[params]
  tagLine = "Graphic Artist - Web Designer - Illustrator"
  homePosts = 3
  homeProjects = 6
  gitHub = "joseph-mccarthy"
  twitter = "joebmccarthy"
  locationLineOne = "Harlow, Essex"
  locationLineTwo = "United Kingdom"
  aboutLeft = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization."
  aboutRight = "You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!"
  homeButtonText = "Free Donwload"
  homeButtonLink = "https://wwww.google.com" 
  homeButtonIcon = "fa-download"

[[menu.main]]
    name = "About"
    weight = -100
    identifier = "about"
[[menu.main]]
    name = "Projects"
    weight = -110
    identifier = "projects"
[[menu.main]]
    name = "Posts"
    weight = -120
    identifier = "posts"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "category"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10