baseURL = 'https://joseph-mccarthy.github.io'
languageCode = 'en-us'
title = 'Joseph McCarthy'

theme = "freelancer"
summaryLength=40
paginate=9


[params]
  tagLine = "Developer - Dreamer - Potato"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "I'm a full time developer which is mostly around Java and DevOps. I'm also a father of a little boy, who keeps me active and on my toes. I'm counting it as exercise, because I need it. Also it keeps my Fitbit a little happier."
  aboutRight = "Out of work my interests vary. I enjoy taking pictures, and generally spending time outdoors walking. I have created this site so I can keep track of what I'm up to and focus more on trying to get some Open Source projects running."

[params.location]
  lineOne = "Harlow, Essex"
  lineTwo = "United Kingdom" 

[params.sbform]
      token = ""

[[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/joseph-mccarthy"


[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[markup]
  [markup.highlight]
    margin = 10
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'friendly'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
     [outputFormats.RSS]
         mediaType = "application/rss+xml"
         baseName = "feed"
